---
# control
control:
  fed: '1'
  num_users: '100'
  frac: '0.1'
  data_split_mode: 'iid'
  model_split_mode: 'fix'
  model_mode: 'a1'
  norm: 'bn'
  scale: '1'
  mask: '1'
# data
data_name: CIFAR10
subset: label
batch_size:
  train: 128
  test: 128
shuffle:
  train: True
  test: False
num_workers: 0
model_name: resnet18
metric_name:
  train:
    - Loss
    - Accuracy
  test:
    - Loss
    - Accuracy
# optimizer
optimizer_name: Adam
lr: 3.0e-4
momentum: 0.9
weight_decay: 5.0e-4
# scheduler
scheduler_name: None
step_size: 1
milestones:
  - 100
  - 150
patience: 10
threshold: 1.0e-3
factor: 0.5
min_lr: 1.0e-4
# experiment
init_seed: 0
num_experiments: 1
num_epochs: 200
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# other
save_format: pdf